name: React CD

on:
  push:
    branches:
      - feature/ci-cd
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: CD Pipeline Started
        run: echo "CI completed successfully. Ready for deployment."